Update ValidateUnityLicense.yml

diff --git a/.github/workflows/ValidateUnityLicense.yml b/.github/workflows/ValidateUnityLicense.yml
--- a/.github/workflows/ValidateUnityLicense.yml
+++ b/.github/workflows/ValidateUnityLicense.yml
@@ -17,8 +17,14 @@ jobs:
         env:
           UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
         run: |
-          mkdir -p ~/.local/share/unity3d/Unity/
-          echo "$UNITY_LICENSE" | tr -d '\n' | base64 --decode > ~/.local/share/unity3d/Unity/Unity_lic.ulf
+         mkdir -p ~/.local/share/unity3d/Unity/
+         echo "$UNITY_LICENSE" | tr -d '\n' | base64 --decode > ~/.local/share/unity3d/Unity/Unity_lic.ulf
+         if [ $? -ne 0 ]; then
+         echo "Failed to decode UNITY_LICENSE. Please ensure it is a valid base64 string."
+         exit 1
+         fi
+         echo "License file successfully created."
+
 
       - name: Install Unity and Validate License
         uses: game-ci/unity-builder@v2
